export const protectedRoutes = [
  // "/login",
  // "/admin",
  // "/admin/:page",
  // "/landlord",
  // "/landlord/:page",
  // "/tenant",
  // "/tenant/:page",
  // "/create-listing",
  // "/create-rental-request",
  "/create-rental-request",
  "/create-listing",
  "/login",

  "/admin",
  "/admin/:page",
  "/tenant",
  "/tenant/:page",
  "/tenant",
  "/tenant/:page",
  "/landlord",
  "/landlord/:page",
  "/orders-view",
  "/verify-order",
];
